services:
  frontend:
    # restart: always # Uncomment for production
    build: 
      context: .
      dockerfile: frontend.Dockerfile
    ports:
    - 3000:3000

  backend:
    # restart: always # Uncomment for production
    build: 
      context: .
      dockerfile: backend.Dockerfile
    ports:
    - 4000:4000
  
  database:
    # restart: always # Uncomment for production
    image: "mongo:latest"
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: "root"
      MONGO_INITDB_ROOT_PASSWORD: "password"
    volumes: 
      - database:/data/db

volumes:
  database:
